on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install pkg
        run: npm install -g pkg

      - name: Build binary
        env:
          PKG_TARGET: ${{ matrix.os == 'windows-latest' && 'node20-win-x64' || (matrix.os == 'macos-latest' && 'node20-macos-x64') || 'node20-linux-x64' }}
        run: |
          # Determine the output filename (add .exe on Windows)
          OUT_NAME="twitch-chat-overlay-local${{ matrix.os == 'windows-latest' && '.exe' || '' }}"
          pkg . --targets $PKG_TARGET --output $OUT_NAME

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: twitch-chat-overlay-local${{ runner.os == 'Windows' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            twitch-chat-overlay-local-linux
            twitch-chat-overlay-local-macos
            twitch-chat-overlay-local.exe
